routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();

Route::get('/home', 'HomeController@index');
Route::get('/', 'HomeController@index');


Route::get('/threads', 'ThreadsController@index');
Route::get('/threads/{channel}/{thread}', 'ThreadsController@show');
Route::delete('/threads/{channel}/{thread}', 'ThreadsController@destroy');
Route::get('/threads/create', 'ThreadsController@create');
Route::post('/threads', 'ThreadsController@store');


Route::post('/threads/{channel}/{thread}/replies', 'RepliesController@store');
Route::delete('/replies/{reply}', 'RepliesController@destroy');
Route::patch('/replies/{reply}', 'RepliesController@update');

Route::get('/threads/{channel}', 'ThreadsController@index');

Route::post('/replies/{reply}/favorites', 'FavoritesController@store');

Route::get('/profiles/{user}', 'ProfilesController@show')->name('profile');

app/Favoritable.php
<?php

namespace App;


use Illuminate\Support\Facades\Auth;

trait Favoritable
{

    public function favorites()
    {
        return $this->morphMany(Favorite::class, 'favorited');
    }

    public function favorite()
    {
        $this->favorites()->create(['user_id' => Auth::id()]);
    }

    public function isFavorited()
    {
        return !!$this->favorites->where('user_id', Auth::id())->count();
    }

    public function getFavoritesCountAttribute()
    {
        return $this->favorites->count();
    }
}

app/Thread.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Thread extends Model
{
    use RecordsActivity;

    protected $with = ['creator', 'channel'];

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('replyCount', function($builder) {
           $builder->withCount('replies');
        });

        static::deleting(function ($thread) {
            $thread->replies->each->delete();
        });
    }

    public function path()
    {
    	return "/threads/{$this->channel->slug}/{$this->id}";
    }

    public function replies()
    {
    	return $this->hasMany(Reply::class);
    }

    public function creator()
    {
    	return $this->belongsTo(User::class, 'user_id');
    }

    public function addReply($reply)
    {
    	return $this->replies()->create($reply);
    }

    public function channel()
    {
        return $this->belongsTo(Channel::class);
    }

    public function scopeFilter($query, $filters)
    {
        return $filters->apply($query);
    }
}

app/Http/Controllers/ThreadsController.php
<?php

namespace App\Http\Controllers;

use App\Thread;
use App\Channel;
use App\Filters\ThreadFilters;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ThreadsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }

    /**
     * Display a listing of the resource.
     *
     * @param Channel $channel
     * @param ThreadFilters $filters
     * @return \Illuminate\Http\Response
     */
    public function index(Channel $channel, ThreadFilters $filters)
    {
        $threads = $this->getThreads($channel, $filters);


//        if(request()->wantsJson()) {
//            return $threads;
//        }

        return view('threads.index', compact('threads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('threads.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'body' => 'required',
            'channel_id' => 'required|exists:channels,id'
        ]);

        $thread = Thread::create([
            'user_id' => Auth::id(),
            'channel_id' => $request->channel_id,
            'title' => $request->title,
            'body' => $request->body
        ]);

        return redirect($thread->path())
            ->with('flash', 'Your thread has been published');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function show($channel, Thread $thread)
    {
        return view('threads.show', [
            'thread' => $thread,
            'replies' => $thread->replies()->paginate(20)
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function edit(Thread $thread)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Thread $thread)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function destroy($channel, Thread $thread)
    {
        $this->authorize('update', $thread);

        $thread->delete();

        if (request()->wantsJson()) {
            return response([], 204);
        }


        return redirect('/threads');
    }

    /**
     * @param Channel $channel
     * @param ThreadFilters $filters
     * @return mixed
     */
    protected function getThreads(Channel $channel, ThreadFilters $filters)
    {
        $threads = Thread::latest()->filter($filters);

        if ($channel->exists) {

            $threads->where('channel_id', $channel->id);

        }

        $threads = $threads->get();

        return $threads;
    }
}

resources/views/threads/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Forum Threads</div>

                <div class="card-body">
                    <div class="row justify-content-center">
				        <div class="col-md-8">
				            <form method="POST" action="/threads">
				                {{ csrf_field() }}

								<div class="form-group">
				                	<label for="channel_id">Choose a channel:</label>
				                	<select name="channel_id" id="channel_id" class="form-control" required>
				                		<option value="">Choose one</option>
				                		@foreach ($channels as $channel)
				                			<option value="{{ $channel->id }}" {{ old('channel_id') == $channel->id ? 'selected' : '' }}>{{ $channel->slug }}
				                			</option>
				                		@endforeach
				                	</select>
								</div>
								
								<div class="form-group">
				                	<label for="title">Title:</label>
				                	<input type="text" name="title" id="title" class="form-control" value="{{ old('title') }}" required>
								</div>

				                <textarea name="body" id="body" class="form-control" rows="8" value="{{ old('body') }}" required>
				                	
				                </textarea>
								
								<div class="form-group">
				                	<button type="submit" class="btn btn-primary">Submit</button>
								</div>

								@if ($errors->any())
								    <div class="alert alert-danger">
								        <ul>
								            @foreach ($errors->all() as $error)
								                <li>{{ $error }}</li>
								            @endforeach
								        </ul>
								    </div>
								@endif
				            </form>				        
				        </div>
				    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/threads/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @forelse ($threads as $thread)
                    <div class="card text-center">
                        <h5 class="card-header">
                            <a href="{{ $thread->path() }}">
                                {{ $thread->title}}
                            </a>


                        </h5>

                        <div class="card-body">

                            <p class="card-text">{{ $thread->body }}</p>

                        </div>
                        <div class="card-footer text-muted">
                            <a href="{{ $thread->path() }}">
                                {{ $thread->replies_count }} {{ str_plural('reply', $thread->replies_count) }}
                            </a>
                        </div>
                    </div>
                @empty
                    <p>No available threads..</p>
                @endforelse
            </div>
        </div>
    </div>
@endsection

resources/views/threads/reply.blade.php
<reply :attributes="{{ $reply }}" inline-template v-cloak>

    <div id="reply-{{ $reply->id }}" class="card">
        <div class="card-header">
            <a href="{{ route('profile', $reply->owner) }}"> {{ $reply->owner->name }}</a>
            said {{ $reply->created_at->diffForHumans() }}

            <div>
                <form method="POST" action="/replies/{{ $reply->id }}/favorites">

                    {{ csrf_field() }}
                    <button type="submit" class="btn btn-default" {{ $reply->isFavorited() ? 'disabled' : '' }}>
                        {{ $reply->favorites_count }} {{ str_plural('Favorite', $reply->favorites_count) }}
                    </button>
                </form>
            </div>
        </div>

        <div class="card-body">
            <div v-if="editing">
                <div class="form-group">
                    <textarea class="form-control" v-model="body"></textarea>
                </div>

                <button class="btn btn-primary btn-sm" @click="update">Update</button>
                <button class="btn btn-default btn-sm" @click="editing = false">Cancel</button>
            </div>

            <div v-else v-text="this.body">

            </div>
        </div>

        @can('update', $reply)
            <div class="card-footer">
                <button class="btn btn-warning btn-sm" @click="editing = true">Edit</button>
                <button class="btn btn-danger btn-sm" @click="destroy">Delete</button>
            </div>
        @endcan

    </div>

</reply>

resources/views/threads/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    @can ('update', $thread)
                        <div>
                            <form action="{{ $thread->path() }}" method="post">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}

                                <button class="btn btn-primary" type="submit">Delete Thread</button>

                            </form>
                        </div>
                    @endcan

                    <a href="{{ route('profile', $thread->creator) }}">{{ $thread->creator->name }}</a> Posted:
                    {{ $thread->title }}
                </div>

                <div class="card-body">
                    {{ $thread->body }}
                </div>
            </div>

            @foreach($replies as $reply)

                @include('threads.reply')

            @endforeach

            {{ $replies->links() }}

            @auth

                <form method="POST" action="{{ $thread->path() . '/replies' }}">
                    {{ csrf_field() }}
                    <textarea name="body" id="body" class="form-control" rows="5" placeholder="Add a comment"></textarea>

                    <button type="submit" class="btn btn-default">Submit</button>
                </form>

            @endauth

            @guest

                <p class="text-center"> <a href="{{ route('login') }}">Sign in</a> to post a reply.</p>

            @endguest

        </div>

        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <a href="">{{ $thread->creator->name }}</a> Posted:
                    {{ $thread->title }}
                </div>

                <div class="card-body">
                    <p>
                        This thread was published {{ $thread->created_at->diffForHumans()  }} by
                        <a href="">{{ $thread->creator->name }}</a>, and currently
                        has {{ $thread->replies_count }} {{ str_plural('comment', $thread->replies_count) }}.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection